### ISSUE TITLE
host not found in upstream *:7777

### ISSUE THREAD

**Issue by SashkaNebesny** [Papka24/Papka24-core#20]
![ng](https://user-images.githubusercontent.com/29460465/29248710-8c8e5c7a-8027-11e7-8611-f461d4cfa50f.PNG)

> server_1    |   ... 11 more
server_1    | 170813-09:50:23.175 [Main:247] error
server_1    | java.net.SocketException: Unresolved address
server_1    |   at sun.nio.ch.Net.translateToSocketException(Net.java:131)
server_1    |   at sun.nio.ch.Net.translateException(Net.java:157)
server_1    |   at sun.nio.ch.Net.translateException(Net.java:163)
server_1    |   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:                                76)
server_1    |   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind                                ToChannelAndAddress(TCPNIOBindingHandler.java:131)
server_1    |   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind                                (TCPNIOBindingHandler.java:88)
server_1    |   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPN                                IOTransport.java:238)
server_1    |   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPN                                IOTransport.java:218)
server_1    |   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPN                                IOTransport.java:209)
server_1    |   at org.glassfish.grizzly.http.server.NetworkListener.start(Netwo                                rkListener.java:723)
server_1    |   at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer                                .java:277)
server_1    |   at com.sun.jersey.api.container.grizzly2.GrizzlyServerFactory.cr                                eateHttpServer(GrizzlyServerFactory.java:329)
server_1    |   at com.sun.jersey.api.container.grizzly2.GrizzlyServerFactory.cr                                eateHttpServer(GrizzlyServerFactory.java:346)
server_1    |   at com.sun.jersey.api.container.grizzly2.GrizzlyServerFactory.cr                                eateHttpServer(GrizzlyServerFactory.java:245)
server_1    |   at ua.papka24.server.Main.main(Main.java:214)
server_1    | Caused by: java.nio.channels.UnresolvedAddressException: null
server_1    |   at sun.nio.ch.Net.checkAddress(Net.java:101)
server_1    |   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelIm                                pl.java:218)
server_1    |   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:                                74)
server_1    |   ... 11 common frames omitted

Всё делал чётко по инструкции. Сертификаты сначала подсунул коммерческие, потом самоподписные ...вроде вебсервер должен был их съесть.
И я не могу разобраться куда вебсервер пишет логи..

**Comment by VladyslavKurmaz** [comment]
Добавь сюда свой .env file.
...
Пока могу предположить, что ты изменил одну из переменных
SERVER_LOCAL_DOMAIN=server
...
По этому внутреннему DNS имени nginx docker образ находит java backend docker.
Посмотрю, возможно  ли это убрать как параметр из настроек 
...

> И я не могу разобраться куда вебсервер пишет логи..
* тебе нужно запустить систему в detached режиме ./up.sh -d
* зайти в докер контейнер ngnix
```
$ docker ps
$ docker exec -it <nginx_container_id> bash
```
https://ruhighload.com/post/%D0%9B%D0%BE%D0%B3%D0%B8+error_log+%D0%B8+access_log+%D0%B2+Nginx_20160706

**Comment by SashkaNebesny** [comment]
> SERVER_DOMAIN=localhost
> SERVER_LOCAL_DOMAIN=srv
> SERVER_DOMAIN_ALIAS=zokb.pp.ua
> SERVER_DOMAIN_MOBILE=m.localhost
> 
> SERVER_TYPE=nginx
> 
> POSTGRES_USER=papka24
> POSTGRES_PASSWORD=papka24
> POSTGRES_DB=papka24
> 
> RECAPTCHA_CLIENT=6_d____________________________________________rKii6a
> RECAPTCHA_SERVER=6_d___________________________________________DYIxT

Да, параметр SERVER_LOCAL_DOMAIN менял, верно

**Comment by SashkaNebesny** [comment]
Запустился ..сертефикат подтянулся ..все хорошо. Только вот при регистрации ошибка 500, после того как проходишь проверку на работа или человека)
`static_1    | *1.2*9.4*.6* - - [13/Aug/2017:13:05:13 +0000] "POST /api/reg/ HTTP/1.1" 500 3406 "https://d*c.**s.pp.ua/" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"`
![554454554](https://user-images.githubusercontent.com/29460465/29249921-c4d5bdd4-8041-11e7-8164-a8498e2633a3.PNG)

**Comment by VladyslavKurmaz** [comment]
> А еще он не может найти в /usr/share/nginx/* 
Там есть маленькая проблема со сборкой фронтенда, первы раз - не все собирается, при повторном запуске все - ок. Это пока не критикал - буду лечить позже
...
> Только вот при регистрации ошибка 500
Это как раз то, над чем сейчас работаю #16 
Один из авторов системы, отключил редис - теперь надо переподнять собственный почтовый сервис

**Comment by SashkaNebesny** [comment]
Проблема с регистрацией исчезла. Ошибки 500 нет. Но, после прохождения проверки вылазит сообщение, что майже все готово - смотрите почту. На почту ничего не пришло, хотя EMAIL_SERVER_DOMAIN настроил. Только меня смущает то, что я прописал 587 порт и почтовый сервер использует TLS соединение.
nginx не проксирует картинки - теперь вопрос ...для решение проблемы нужно изменять файл конфига nginx: Papka24-core/devops/static-nginx/ или уже в самом докере? И как заново пересобрать докер, если например были изменения в .env?
PS: я не волшебник, только учусь...

**Comment by VladyslavKurmaz** [comment]
> На почту ничего не пришло

Аналогично. Фикс с почтой длал не я. Будем дебажить.

> Только меня смущает то, что почтовый сервер использует TLS соединение (587 port).
Это где ты такое увидел? Java backend общается c postfix по 25 порту

> И как заново пересобрать докер, если например были изменения в .env
Останавливаешь кластер: <ctrl> + C, если запускал через ./up.sh без параметра -d
Удаляешь образы - ./down.sh
Меняеть что тебе нужно
Перезапускаешь кластер ./up.sh -d

**Comment by SashkaNebesny** [comment]
А может лучше будет, если реализация почтового сервиса будет, например, как у Альфркско? ...чтобы можно было работать с любым почтовым сервисом ..даже публичным.

**Comment by SashkaNebesny** [comment]
В конфиг nginx я добавил:
```
location ~* \.(jpg|jpeg|gif|png|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|xml|docx|xlsx)$ {
root /usr/share/nginx/html/;
index index.html index.htm;
access_log off;
expires 30d;
  error_page 404 = @fallback;
  proxy_cache_valid 404 1m;
}
```
```
location @fallback { 
proxy_pass http://127.0.0.1:80;  
proxy_set_header X-Real-IP $remote_addr; 
proxy_set_header X-Forwarded-for $remote_addr; 
proxy_set_header Host $host; 
} 
```
Правда, на счет @fallback я не уверен, но теперь картинки вместе со стилем отображаются...

**Comment by VladyslavKurmaz** [comment]
> А может лучше будет, если реализация "почты" будет, например, как у Альфркско? ...чтобы можно > было работать с любым почтовым сервисом ..даже публичным.

Согласен. Добавлю в параметры FQDN для почтового сервера. По-умолчанию будет **mail** это имя postfix в контейнере, но можно переопределить на что-то внешнее

**Comment by SashkaNebesny** [comment]
Скажите, а можно ли как-то пройти регистрацию без подтверждения по емейлу?))

**Comment by kovalevskij-d** [comment]
Можно в лог включить запись ссылки на регистрацию и активировать из логов.
