### ISSUE TITLE
User postfix instance to send emails

### ISSUE THREAD

**Issue by VladyslavKurmaz** [Papka24/Papka24-core#27]
## Prerequisites
1. Use postfix instance inside cluster, define next properties inside .env
```
EMAIL_SERVER_DOMAIN=smtp.example.com
EMAIL_SERVER_PORT=25
EMAIL_SERVER_USER=user
EMAIL_SERVER_PASSWORD=password
```
2. Run cluster ./up.sh

## Expected behaviour
1. No error(s) in log
2. Email is sent during registration

## Actual behavior
1. Front-end shows no error(s)
2. Error(s) in log
static_1    | 176.241.139.47 - - [19/Aug/2017:08:58:41 +0000] "POST /api/reg/ HTTP/1.1" 200 0 "https://95.85.56.80/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
server_1    | 170819-08:58:49.874 [EmailQueue:172] fail to send email
server_1    | com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.example.com, 25; timeout -1
server_1    |   at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
server_1    |   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
server_1    |   at javax.mail.Service.connect(Service.java:364)
server_1    |   at javax.mail.Service.connect(Service.java:245)
server_1    |   at ua.papka24.server.api.helper.EmailQueueConsumer.sendEmails(EmailQueueConsumer.java:106)
server_1    |   at ua.papka24.server.api.helper.EmailQueueConsumer.run(EmailQueueConsumer.java:182)
server_1    |   at java.lang.Thread.run(Thread.java:748)
server_1    | Caused by: java.net.UnknownHostException: smtp.example.com
server_1    |   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
server_1    |   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
server_1    |   at java.net.Socket.connect(Socket.java:589)
server_1    |   at java.net.Socket.connect(Socket.java:538)
server_1    |   at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:312)
server_1    |   at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
server_1    |   at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)

![image](https://user-images.githubusercontent.com/1977961/29485165-10419e44-84d6-11e7-8329-74a03150f8dd.png)

**Comment by wooddy** [comment]
#30 по работе с postfix

по калбеку от почтовика (не корректное отображение Майже все готово!)  сложнее - письмо помещаются в очередь (по идее будет доставленно как только будет доступен почтовый сервер).
отправлять письма может не та же нода которая приняла запрос.
